[workspace]
members = [
    "wasplib",
    "contracts/donatewithfeedback",
    "contracts/fairauction",
    "contracts/fairroulette",
    "contracts/helloworld",
    "contracts/increment",
    "contracts/tokenregistry",
    "contracts/erc20",
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

