[workspace]
members = ["wasplib", "donatewithfeedback", "fairauction", "fairroulette", "increment", "tokenregistry"]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

